language: python
install: pip install tox
os: linux
dist: xenial
jobs:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.7"
    env: TOX_ENV=py37
  - python: "3.7"
    env: TOX_ENV=pycodestyle
  - python: "3.7.9"
    env: TOX_ENV=pidiff
  - python: "3.7"
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: "3.7"
    env: TOX_ENV=docs
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs

deploy:
  # Adding a new tag automatically releases to PyPI.
  provider: pypi
  username: __token__
  password:
    secure: NymjXDoM/g0S6cqh4+v6fv0Mf14iLpiZRQMiWs6zIIP4IrHQAkLkJRngop20tM7ivJbnGsfGd7qLNjrIWfSb6eGkx6xLZpEvMJn95Fny+pc5DbHRORX14vcXC8XyNLeTU4BW0CpLKPDTlTIjWAlRq0lXjwBG2+Pe8pvHJcZB9jfPvjzV+VzKAyRncNVhRt+ce+9VZm3bF2lSbXVhcFlAEvclTJHPxRyfLh4VYDVXMdgIDckcOQLnNq8+8uqBVEweQQUO8GYqIS55KouglNK6slpk1VJcp4cVMMer1V/Hc8noZHUMibGEqQDotUcgfGTtRTl1P3soxhhprh7ISVy3oL0/ZnCu44IG7k6hBCg7w87LhuBtHtbkMAsJY8yJ/sjj9gJBULtuRgx6Sz5K+4/pvfRErb/F3Xmgw/SPICBMI4oxvQUB51YAfeywruv4r54nRBkWBDn3fCzORvOEU0HSlPK/rMINDcAB6pExbdn8WbUDVN5CbSPwFdDRxG3Ai41peD0x6Bw17562VPaVHx5U6Q+wBWqDH3Dg8IjM+9ndcaO6SP70JVqWfFe0BxEFRV+g4026AJE46J8BM11yfcB5+LgF/hOucSWWjf5doTQemZYgVtey33823EhhD8Z7qN84lnfc2cSQrtzSTGkspjd4jFaT0UsahrPh2xLjghTmpm0=
  on:
    tags: true
    # Only one of the environments in the matrix should have
    # deployments enabled. It's mostly arbitrary which one,
    # but best to select some Python 3.x so up-to-date tools
    # are used during release.
    condition: $DEPLOY = 1
  skip_existing: true

